In [2]:
import numpy as np

# Exercise 1
Create a 1D NumPy array of numbers from 0 to 9

In [3]:
#arr = np.array([1,2,3,4,5,6,7,8,9])
arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Exercise 2: Convert 1D array to 2D
Write a code to convert a 1D array to a 2D array with 2 rows.

In [4]:
arr = np.arange(6)
print(f"original arr: {arr}")
arr = arr.reshape(2,3)
arr

original arr: [0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

# Exercise 3: Print Array Attributes
Instructions: Print the following attributes of the array:

The shape of the array.
The number of array dimensions.
The size of each element in bytes.

In [5]:

my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
my_array.shape,my_array.ndim,my_array.itemsize

((4, 2), 2, 2)

# Exercise 4: Create a 3×3 NumPy array of all True

In [6]:
arr = np.ones((3,3),dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Exercise 5: Extract the documentation of NumPy’s arange() function

In [7]:
np.info('arange')

     *** Found in numpy ***
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    S

In [8]:
arr =np.arange(0,100,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

# Exercise 6: Create a 1D array filled with zeros and another filled with ones

In [9]:
arr1 = np.ones(5)
arr0 = np.zeros(5)
arr1,arr0

(array([1., 1., 1., 1., 1.]), array([0., 0., 0., 0., 0.]))

# Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50

In [10]:
arr = np.linspace(5,50,10)
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

# Exercise 8: Convert a Python list into a NumPy array

In [11]:
py_list = [1, 2, 3, 4, 5]
arr = np.array(py_list)
arr

array([1, 2, 3, 4, 5])

# Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9

In [12]:
arr = np.arange(9)
arr.nbytes

72

# Exercise 10: Reverse a 1D NumPy array

In [13]:
arr[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

# Exercise 11: Create a 3×3 identity matrix


In [15]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Exercise 12: Create a 4×4 array and extract its first row and last column

In [16]:
arr = np.random.randint(0,100,size=(4,4))
arr,arr[0,:],arr[:,3]

(array([[71,  0, 19, 21],
        [80,  9, 10, 20],
        [10, 40, 83, 72],
        [93, 69, 27, 82]], dtype=int32),
 array([71,  0, 19, 21], dtype=int32),
 array([21, 20, 72, 82], dtype=int32))

# Exercise 13: Extract Odd Rows and Even Columns
Extract an array of odd rows and even columns from below NumPy array.

Problem Breakdown

Rows: In programming, indexing starts at 0. Odd-indexed rows would be rows 1 and 3.
Columns: Even-indexed columns would be columns 0 and 2.

In [22]:
sampleArray = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48], 
    [51, 54, 57, 60]
])
# Slice 1 (Size 8)
part1 = sampleArray[1::2, :].flatten()

# Slice 2 (Size 10)
part2 = sampleArray[:, 0::2].flatten()

# Glue them into one long array of size 18
combined = np.concatenate((part1, part2))
combined

array([15, 18, 21, 24, 39, 42, 45, 48,  3,  9, 15, 21, 27, 33, 39, 45, 51,
       57])

# Exercise 14: Stack arrays horizontally

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Exercise 15: Slice the first two rows and first two columns from a 4×4 array
Write a code to Create a 4×4 NumPy array and extract the first two rows and first two colum

In [24]:
arr = np.random.randint(0,100,size=(4,4))
arr,arr[0:2,0:2]

(array([[56, 71, 75, 13],
        [24, 57, 82,  2],
        [53, 89, 23, 17],
        [78, 49, 64, 21]], dtype=int32),
 array([[56, 71],
        [24, 57]], dtype=int32))

# Exercise 16: Replace all odd numbers in a NumPy array with -1

In [25]:
arr =  np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[arr%2==1] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

# Exercise 17: Get the indices of non-zero elements in an array


In [27]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr)
indices

(array([0, 2, 4, 6]),)

# Exercise 18: Find the common items between two arrays


In [28]:
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])
np.intersect1d(a,b)


array([2, 4, 8])

# Exercise 19: Perform arithmetic operations on two NumPy arrays element-wise
Add two NumPy arrays element by element.
Multiply two NumPy arrays element by element.

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a*b,a+b

(array([ 4, 10, 18]), array([5, 7, 9]))

# Exercise 20: Matrix multiplication
Write a code to compute the dot product of two NumPy arrays

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

np.int64(32)

# Exercise 21: Compute the mean, median, and standard deviation of a NumPy array
Mean: Average of numbers.
Median: Middle value when sorted.
Standard Deviation: How spread out values are from the mean.

In [31]:
arr = np.array([10, 20, 30, 100, 200, 300])
np.mean(arr),np.median(arr),np.std(arr)

(np.float64(110.0), np.float64(65.0), np.float64(107.08252269472673))

# Exercise 22: Remove common items from array

In [33]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
a[~(np.isin(a,b))]

array([1, 2, 3, 4])

# Exercise 23: Normalize a NumPy array (values between 0 and 1)

In [35]:
arr = np.array([10, 20, 30, 40, 50])
(arr-arr.min())/(arr.max()-arr.min())

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Exercise 24: Get the positions where elements of array a and b match

In [36]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])
np.where(a==b)

(array([0, 2]),)

# Exercise 25: Extract numbers from an array
Write a code to extract all numbers from an array that are between 5 and 10 (inclusive).

In [45]:
arr = np.arange(15)
arr[(arr >= 5) & (arr <= 10)]

array([ 5,  6,  7,  8,  9, 10])

# Exercise 26: Create a random 3×2 matrix and find its maximum and minimum values

In [50]:
ran = np.random.random(size=(3,2))
ran,ran.max(),ran.min()

(array([[0.03114081, 0.76132797],
        [0.30689064, 0.55182636],
        [0.59109897, 0.10578988]]),
 np.float64(0.7613279731107222),
 np.float64(0.03114081190740836))

# Exercise 27: Sorting a NumPy array based on a specific column

In [54]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
sampleArray[sampleArray[:,1].argsort()]
sampleArray[[2,0,1]]

array([[53, 94, 66],
       [34, 43, 73],
       [82, 22, 12]])

# Exercise 28: Delete and Insert a Column in a NumPy Array
Delete the second column from a given array and insert the following new column in its place.

In [55]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumnToAdd = np.array([10, 10, 10])
dele = np.delete(sampleArray,1,axis=1)
newarr = np.insert(dele,1,newColumnToAdd,axis=1)
newarr

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

# Exercise 29: Swap column 1 and 2 in a 2D array


In [56]:
arr = np.arange(9).reshape(3, 3)
arr[:,[1,2]]=arr[:,[2,1]]
arr

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

# Exercise 30: Generate 10 random integers between 1 and 100

In [57]:
np.random.randint(1,100,size=10)

array([51, 10, 79, 53, 83, 97, 12, 24, 87, 58], dtype=int32)

# Exercise 31: Create a 3×3 array of random integers and sort it row-wise

In [61]:
arr = np.random.randint(1,100,size=(3,3))
np.sort(arr,axis = 1)
arr.sort(axis=1)
arr


array([[15, 45, 93],
       [13, 36, 52],
       [ 9, 72, 76]], dtype=int32)